name: 'Restore composer cache'
description: ''
runs:
    using: composite
    steps:
        - uses: actions/cache@v3
          env:
              cache-name: composer-deps-v1
          with:
              path: |
                  ~/.composer
                  ./vendor
              key: ${{ env.cache-name }}-${{ hashFiles( 'composer.lock' ) }}
              restore-keys: |
                  ${{ env.cache-name }}-
